services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - TZ=America/New_York
    volumes:
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - /mnt/media:/media:ro
    ports:
      - 8096:8096
    networks:
      - proxy-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.codistech.live`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=proxy-internal"

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./plex-config:/config
      - /mnt/media/tv:/tv:ro
      - /mnt/media/movies:/movies:ro
      - /mnt/media/music:/music:ro
      - /mnt/media/anime:/anime:ro
      - /mnt/media/p90x:/p90x:ro
      - /mnt/media/youtube:/youtube:ro

networks:
  proxy-internal:
    external: true
