services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - N8N_HOST=n8n.local.codistech.live
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://n8n.local.codistech.live/
      - WEBHOOK_URL=https://n8n-webhook.codistech.live/
      - GENERIC_TIMEZONE=America/Detroit
      - N8N_PROXY_HOPS=1
      - N8N_USER_MANAGEMENT_DISABLED=true    
    volumes:
      - ./data:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - proxy-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.local.codistech.live`)"                        
      - "traefik.http.routers.n8n.entrypoints=https"                                            
      - "traefik.http.routers.n8n.tls.certresolver=cloudflare"                                  
      - "traefik.http.routers.n8n.middlewares=authentik@file"                                   
      - "traefik.http.routers.n8n-webhook.rule=Host(`n8n-webhook.codistech.live`)"              
      - "traefik.http.routers.n8n-webhook.entrypoints=https"                                    
      - "traefik.http.routers.n8n-webhook.tls.certresolver=cloudflare"                          
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"                               
      - "traefik.docker.network=proxy-internal"     
      - "traefik.http.routers.n8n-api.rule=Host(`n8n.local.codistech.live`) && PathPrefix(`/api`)"                
      - "traefik.http.routers.n8n-api.entrypoints=https"                               
      - "traefik.http.routers.n8n-api.tls.certresolver=cloudflare"                         
      - "traefik.http.routers.n8n-api.priority=100"   
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    networks:
      - proxy-internal

networks:
  proxy-internal:
    external: true
    