services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    depends_on:
      - whisper
      - piper
      - openwakeword
    networks:
      - proxy-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.entrypoints=http"
      - "traefik.http.routers.homeassistant.rule=Host(`ha.local.codistech.live`)"
      - "traefik.http.middlewares.homeassistant-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homeassistant.middlewares=homeassistant-https-redirect"
      - "traefik.http.routers.homeassistant-secure.entrypoints=https"
      - "traefik.http.routers.homeassistant-secure.rule=Host(`ha.local.codistech.live`)"
      - "traefik.http.routers.homeassistant-secure.tls=true"
      - "traefik.http.routers.homeassistant-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.homeassistant-secure.service=homeassistant"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.docker.network=proxy-internal"

  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model small-int8 --language en
    volumes:
      - ./whisper/data:/data
    restart: unless-stopped
    networks:
      - proxy-internal

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice en_US-lessac-medium
    volumes:
      - ./piper/data:/data
    restart: unless-stopped
    networks:
      - proxy-internal

  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    command: --preload-model 'ok_nabu'
    restart: unless-stopped
    networks:
      - proxy-internal
  
  matter-server:
    container_name: matter-server  
    image: ghcr.io/home-assistant-libs/python-matter-server:stable 
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined 
    volumes:
      - ./matter-server:/data 
      - /run/dbus:/run/dbus:ro 
    networks:
      - proxy-internal
    ports:
      - "5580:5580"

networks:
  proxy-internal:
    external: true