services:
  web:
    image: nginx:latest
    container_name: codistech
    volumes:
      - /home/serveradmin/docker_volumes/nginx/templates:/etc/nginx/templates
      - /home/serveradmin/docker_volumes/nginx/html:/usr/share/nginx/html
    environment:
      - NGINX_HOST=nginx.codistech.live
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=Host(`nginx.local.codistech.live`)"
      - "traefik.http.middlewares.nginx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.nginx.middlewares=nginx-https-redirect"
      - "traefik.http.routers.nginx-secure.entrypoints=https"
      - "traefik.http.routers.nginx-secure.rule=Host(`nginx.local.codistech.live`)"
      - "traefik.http.routers.nginx-secure.tls=true"
      - "traefik.http.routers.nginx-secure.service=nginx-service"
      - "traefik.http.services.nginx-service.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy-internal"
    restart: unless-stopped
    networks:
      - proxy-internal
    security_opt:
      - no-new-privileges:true # helps to increase security
networks:
  proxy-internal:
    external: true

