global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'node-docker'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          instance: 'docker-vm'

  - job_name: 'node-pihole'
    static_configs:
      - targets: ['192.168.0.55:9100']
        labels:
          instance: 'pihole-pi'

  - job_name: 'node-unraid'
    static_configs:
      - targets: ['192.168.0.50:9100']
        labels:
          instance: 'unraid'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'proxmox'
    static_configs:
      - targets: ['pve-exporter:9221']
    metrics_path: /pve
    params:
      target: ['192.168.0.90']

  - job_name: 'pihole'
    static_configs:
      - targets: ['pihole-exporter:9617']

  - job_name: 'crowdsec'
    static_configs:
      - targets: ['crowdsec:6060']
